# Generated by Django 3.1.4 on 2021-06-18 14:46

import Intelligence.utils
import django.core.files.storage
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predictions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('pred', models.CharField(blank=True, max_length=255)),
                ('n', models.CharField(blank=True, max_length=255)),
                ('image', imagekit.models.fields.ProcessedImageField(storage=django.core.files.storage.FileSystemStorage(location='H:\\School\\VGGKBSAssignment\\WebApp\\Configurations\\../static_cdn\\media_root'), upload_to=Intelligence.utils.file_upload_path)),
            ],
        ),
    ]
