# Generated by Django 3.1.4 on 2021-06-21 19:32

import Intelligence.utils
import Intelligence.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intelligence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, upload_to=Intelligence.utils.file_upload_path, validators=[Intelligence.validators.validate_file_extension])),
            ],
        ),
        migrations.RenameModel(
            old_name='Predictions',
            new_name='Prediction',
        ),
    ]
