# Generated by Django 3.1.4 on 2021-06-21 20:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Intelligence', '0003_auto_20210621_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
