# Generated by Django 3.1.4 on 2021-06-21 20:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Intelligence', '0004_auto_20210621_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
