
###### Backend

FROM python:3.8.5

ENV PYTHONUNBUFFERED 1
RUN mkdir /app
WORKDIR /app
COPY requirements.txt /app/

RUN apt-get update && apt-get install -y python3-opencv
RUN pip install opencv-python

RUN pip install dj-database-url
RUN pip install -r requirements.txt

COPY . /app/

RUN python3 manage.py collectstatic --settings=Configurations.settings.settings_prod

EXPOSE 5432
EXPOSE 8000




# RUN apt-get update
# RUN apt install -y libgl1-mesa-glx